### ISSUE TITLE
Is it necessary to set offset_x and offset_y when using tecoganDA or basicVSR (bvpp)?

### ISSUE THREAD

**Issue by teijiIshida** [km2ii/JVP_TG-PLUS#150]
Is it necessary to set offset_x and offset_y when using tecoganDA or basicVSR (bvpp)?

**Comment by teijiIshida** [comment]
How do I know if "the output has an offset"? What happen if I just use 0 for both?

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/234343756-dbe3307e-2f73-4a97-87d7-fb96ca6221c3.png)

The offset issue was fixed in v0.3.03.20, now just keep the parameters.

In fact, it is not that this mod problem, but that the official model has an offset, and the official corrected the offset when compositing images.

**The correction is forced to adapt to the official.**

**Comment by teijiIshida** [comment]
Thank you. I will keep both at 0 as instructed.
