### ISSUE TITLE
30 process quantities are short.

### ISSUE THREAD

**Issue by Hellgate4** [km2ii/JVP_TG-PLUS#181]
5 minutes in time
If you process more than 30 files, as you mentioned, the source file will be copied immediately.
The processing after five minutes is then copied directly, making the image appear blurry.

Although it is a commercial sanction, it is judged that the time is too short or the processing number is too small.

Since it is intended to sanction a very long process for commercial use anyway, it is necessary to adjust the number of processes between 10 and 20 minutes or about 100 processes I can tell

Please consider it.

**Comment by cetaph230** [comment]
Agreed. There are many honest hobbyists who want to process an entire movie. Please reconsider the processing limit.

**Comment by Hellgate4** [comment]
> Agreed. There are many honest hobbyists who want to process an entire movie. Please reconsider the processing limit.

I'm not asking you to allow enough process time to proceed with the entire movie.

Even if you study and study, 5 minutes is too short, so I'm asking you to extend it a little more

I agree with not allowing the entire movie to be commercially available, but the current level of time and process is too short, so that's what I said.

I hope there is no mistake in the content.

**Comment by cetaph230** [comment]
Hellgate4 has a good opinion. My opinion is different -- I do not think a processing limit is justified, because there are hobbyists who want to process entire movies and who do not have any intent to distribute or commercialize the results. As someone on Ko-Fi suggested, it may be good for Km2ii to offer a purchase option for a "full" version which does not have any processing limits.

**Comment by newborn2010** [comment]
Yes, we'd like to sponsor it for the full version.

**Comment by wwallace55** [comment]
I agree on creating a full version and trial version like JavPlayer.  Don't mix the design of both product features into one because it will be a mess to manage.  Keep it simple as a creator and for the users.  Lots of other software creators already got this figured out.  No need to reinvent the wheel.
