### ISSUE TITLE
Second TG-AF taking unacceptable time and gpu vram, any aliternative for restoring colour?

### ISSUE THREAD

**Issue by zqvshen** [km2ii/JVP_TG-PLUS#89]
Hello km2ii!
My processing flow is:
m1:basicVSR-pp-af_85000
m2:denoise:td
m3:TG-AF1

Denoise causes the colour of replaced part to be different from the surroundings, and m3:TG-AF1 can restoring it. But m3:TG-AF1 takes 6G gpu vram and 90% time consumption of the whole porcess. 30mins cut takes unacceptable 6hours to porcess.
So is there any aliternative method for restoring colour?

**Comment by zqvshen** [comment]
I find that veai-gcg is an aliternative and save about 50% time when running with 2 paras.

**Comment by km2ii** [comment]
The speed depends on the size of the image processed, 6g vrm is the minimum requirement, not sure what the point of two af models + td.

**Comment by zqvshen** [comment]
Denoise makes the uncensored part darker than the origin and the surroundings. The second AF1 can restore the colour but takes too long.

**Comment by km2ii** [comment]
Denoise will cause this problem, here is a test. Where you can see that after td it gets darker (face) and after using AF1 some brightness restored.

Personally, I don't think should do this, the AF model is useful in suppressing noise and flicker, but it will loses detail, denoise also loses detail. It's not worth consuming a lot of time just to regain brightness. 
Suggest to consider other ways to deal with it, or adding downscale after the td to speed up the conversion.

The following tests are for reference only, due to the different types of mosaic.
![image](https://user-images.githubusercontent.com/55206195/198099031-aafe9581-603e-4d6d-8ae8-55dd01abd783.png)

**Comment by zqvshen** [comment]
thx for your tests and suggestion. I just wonder if you, as the mod author, could know other methods to regain brightness. It's OK if the answer is no. Downscale loses too much detail, so I'm using veai-gcg to do this and save 50% of time.
